name: Heuplus Backend Project

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  RUNNER: ubuntu-22.04      

jobs:  
  run-unit-tests:
    runs-on: ubuntu-22.04
    env:
      CODELYZE_TOKEN: ${{ secrets.CODELYZE_TOKEN }}

    steps:
      - name: Codelyze - Coverage
        uses: codelyze/action@2.1.0
